from typing import Optional, Protocol
from datetime import datetime
from app.domain.models.activation_code import ActivationCode


class ActivationCodeRepository(Protocol):
    async def get_for_user(self, user_id: int) -> Optional[ActivationCode]: ...
    async def create(self, code: ActivationCode) -> ActivationCode: ...
    async def mark_used(self, code_id: int, at: datetime) -> None: ...
    async def increment_attempts(self, code_id: int) -> None: ...
